version: "3.9"
   
services:
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
    restart: always
    # platform: linux/arm64/v8

  web:
    build:
      context: .
      target: dev
    command: make run/devserver
    volumes:
      - ./src:/app/src
      - .env:/app/.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy