name: pull-request-cleanup
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Delete image
        run: |
          curl -u ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }} -X DELETE \
          -H "Accept: application/json" \
          https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/shop-backend/tags/pr-${{ github.event.pull_request.number }}-${{ github.run_number }}/
